[package]
name = "ezkl-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# Name to be imported within python
# Example: import ezkl_lib
name = "ezkl_lib"
crate-type = ["cdylib", "rlib"]


[dependencies]
halo2_proofs = { git = "https://github.com/privacy-scaling-explorations/halo2", tag = "v2023_02_02"}
halo2curves = { git = 'https://github.com/privacy-scaling-explorations/halo2curves', tag = "0.3.1" }
rand = "0.8"
itertools = "0.10.3"
tensorflow = {version = "0.18.0", features = ["eager"], optional = true }
plotters = { version = "0.3.0", optional = true }
tract-onnx = { version = "0.17.7", optional = true }
anyhow = "1.0.65"
clap = { version = "4.0.32", features = ["derive"] }
serde = { version = "1.0.126", features = ["derive"], optional = true  }
serde_json = { version = "1.0.64", optional = true }
log = { version = "0.4.17", optional = true }
tabled = { version = "0.9.0", optional = true}
thiserror = "1.0.38"
hex = "0.4.3"
ethereum_types = { package = "ethereum-types", version = "0.14.1", default-features = false, features = ["std"]}
halo2_wrong_ecc = { git = "https://github.com/privacy-scaling-explorations/halo2wrong", package = "ecc", tag = "v2023_02_02"}
snark-verifier = { git = "https://github.com/privacy-scaling-explorations/snark-verifier", tag = "v2023_02_02"}
regex = "1"
colored = { version = "2.0.0", optional = true}
env_logger = { version = "0.10.0", optional = true}
colored_json =  { version = "3.0.1", optional = true}
tokio = { version = "1.26.0", features = ["macros", "rt"] }
puruspe = "0.2.0"
bincode = "*"

# python binding related deps
pyo3 = { version = "0.18.2", features = ["extension-module", "abi3-py37"], optional = true }
pyo3-log = { version = "0.8.1", optional = true }
# Omit for the time being as ndarrays are not being used
# numpy = { version = "0.18.0", optional = true }


# evm related deps
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ethers = { version = "2.0.1", features = ["ledger"] }
ethers-solc = "2.0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.8", features = ["js"] }


[dev-dependencies]
criterion = {version = "0.3",  features = ["html_reports"]}
tempfile = "3.3.0"
reqwest = "0.11.14"
lazy_static = "1.4.0"
mnist = "0.5"
seq-macro = "0.3.1"
test-case = "2.2.2"
ctor = "0.1.26"
tempdir = "0.3.7"


[[bench]]
name = "accum_affine"
harness = false


[[bench]]
name = "accum_dot"
harness = false


[[bench]]
name = "accum_sum"
harness = false

[[bench]]
name = "pairwise_add"
harness = false


[[bench]]
name = "pairwise_pow"
harness = false


[[bench]]
name = "accum_pack"
harness = false


[[bench]]
name = "accum_matmul"
harness = false


[[bench]]
name = "accum_conv"
harness = false


[[bench]]
name = "accum_sumpool"
harness = false


[[bench]]
name = "relu"
harness = false

[[bench]]
name = "accum_matmul_relu"
harness = false

[[bin]]
name = "ezkl"
test = false
bench = false
required-features = ["ezkl"]

[features]
default = ["ezkl"]
render = ["halo2_proofs/dev-graph", "plotters"]
tensorflow = ["dep:tensorflow"]
onnx = ["dep:tract-onnx"]
python-bindings = ["pyo3", "pyo3-log"]
ezkl = ["onnx", "serde", "serde_json", "log", "colored", "env_logger", "tabled", "colored_json"]
